### PR TITLE
Add CI test for PyPy3

### PR DESCRIPTION
**Pull request by johnthagen**

### CODE REVIEW

**Comment by johnthagen** [comment]
Turns out [PyPy is not compatible with wxPython](https://bitbucket.org/pypy/compatibility/wiki/Home).

**Comment by xesscorp** [comment]
The latest SKiDL release pulls the zyc utility into its own repo and removes the wxpython requirement for SKiDL. Maybe PyPy will work now.

**Comment by johnthagen** [comment]
> The latest SKiDL release pulls the zyc utility into its own repo and removes the wxpython requirement for SKiDL. Maybe PyPy will work now.

@xesscorp That's awesome. I was actually going to suggest something along those lines (i.e. enable people to generate netlists without pulling in a GUI library) but I didn't have enough understanding about skidl to know if that was a valid suggestion or not.

**Comment by johnthagen** [comment]
@xesscorp Wow, the CI is so much faster now that we don't have to build wxPython!

**Pull request closed without merging**
