### PR TITLE
Feature: Add optional fixed hierarchical part naming in netlists

### PR DESCRIPTION
**Pull request by mofarrell**
Kicad's `pcbnew` offers two ways of matching imported netlists to existing footprints in a project (when reimporting the netlist).  By the reference name, or by the `tstamps` field in the netlist.  The default is to use the tstamps field, and this is the preferable way to tie the footprints to the netlist components when the netlist is exported from eeschema since eeschema keeps the tstamps field fixed for a given component.  Prior to this change skidl would populate the tstamps field with a random number.  This meant reimporting a netlist (using default settings) would replace all components, causing you to lose any prior layout work.  Reimporting while tieing components to footprints using reference identifiers is not much better since reference identifiers are assigned in program order, meaning that inserting a component anywhere in your design will offset your references names for the rest of the design.  This could be worked around by always specifying a reference identifier in skidl, but it still causes issues in the presence of subcircuits and pacakages unless you build hierarchical reference names manually (which also end up looking ugly on your PCB silk screen if you want to show them).

This PR changes how tstamps are emitted.  Instead of using a randomly generated identifier at netlist generation time, Parts are assigned an identifier (by default random, but also user assignable) at part creation time.  Similarly the hierarchical name building done in subcircuits is extended to allow the identifier to be user specifiable (currently it is just an incrementing int based on the subcircuit name).  I commandeered the `identifier` parameter to any subcircuit or package in order to implement this, which potentially breaks existing designs using it.

With this PR any design that specifies identifiers for all components, subcircuits and packages can easily be iterated on while performing the PCB layout without losing work.

I currently have this change based on master, but am happy to rebase it onto development if that is helpful.

### CODE REVIEW

**Comment by xesscorp** [comment]
Thanks for making this! It's a good idea.

If you could make this a PR against the development branch, that would be best. Also, don't bother with the isort/black formatting if possible. It obfuscates the functional changes you're making. (I know the contributing guidelines say to do it. I'm going to have to change that.) We can always beautify it later.

Is there a better name for the parameter than the generic `identifier`? Something that indicates what it's used for? `stamp` might work. Or something shorter, at least, like `tag` or `hier_tag`.

**Comment by mofarrell** [comment]
Glad you think it may be useful as well!  Sorry it took a while to get back on this:
- Substitute `s/identifier/tag/g`.  I went for this because it will be nice and concise when building circuits.  It seemed better than `hier_tag` since for the most part user needn't care how it is being used, just that it properly ties their parts to the ones in the pcb layout software.
- Rebase onto `development`
- Remove commit containing the application of the auto formatters from the PR

**Comment by xesscorp** [comment]
Thanks for doing this. Looks good!

Is there a reason the `tag` property of a part can be set and deleted, but it can't be read?

**Comment by mofarrell** [comment]
No particular reason.  I am happy to add a getter.  My thought was that proper uses would look at the `hierarchical_name` read only property, rather than just the tag.  Making the tag unreadable was just to encourage people to do that (or I guess force them to).

**Comment by xesscorp** [comment]
OK, I added the getter method for tag and made a few small changes. I'll merge it. Thanks!

**Pull request merged**
