### PR TITLE
Auto-format code 

### PR DESCRIPTION
**Pull request by flaviut**
(this change is based upon https://github.com/xesscorp/skidl/pull/49. If you don't want that PR, I'd be happy to rebase it)

This change automatically formats the code. In my opinion, this is better than using something like flake8, since it doesn't require any manual changes--whatever the output of the tool is, is the correct formatting. It reduces the mental overhead (for me, at least), by not having to consider code formatting while writing the code and allowing the tool to figure out the right way to do it.

I've updated the `CONTRIBUTING.rst` in order to show the procedure for auto-formatting.

I've also updated the Travis CI file to automatically check formatting.

### CODE REVIEW

**Comment by xesscorp** [comment]
Forgive my ignorance, but is this (more or less) a precommit hook to run YAPF on the code? If so, that's great. I'll take a further look at it and then merge it.

**Comment by flaviut** [comment]
> Forgive my ignorance, but is this (more or less) a precommit hook to run YAPF on the code?

1. The branch name is wrong. I was originally going to use YAPF, but I then decided to use [black](https://github.com/python/black) and [isort](https://github.com/timothycrosley/isort) instead, for reasons I don't remember (YAPF probably crashed or was a pain to configure or something)
2. It's not a pre-commit hook, although there is a CI hook that will ensure that the files are always properly formatted. If you would like to use a pre-commit hook, you should feel free to do that, but I don't think that it's possible to automatically install a pre-commit hook.

Also, while I was modifying the CI code, I also went ahead and added labels & Py 3.6 support to travis, and made the tox config a bit more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by flaviut** [comment]
(also, CI failure is due to incorrectly formatted code. I've removed the "reformat code" commit from this, and I can add it back right before or after you merge this in order to avoid merge conflicts)

**Comment by xesscorp** [comment]
Thanks!

**Comment by flaviut** [comment]
Thanks for merging! If you'd run `isort -y --recursive tests skidl setup.py` and `black skidl tests setup.py`, and commit those changes, that should make the travis job pass again.

**Comment by xesscorp** [comment]
Done. Thanks for the nudge!

**Pull request merged**
