### PR TITLE
Fixed absolute file names used in tests

### PR DESCRIPTION
**Pull request by chenz**

### CODE REVIEW

**Comment by xesscorp** [comment]
Good idea to remove the absolute path to that library. I've done the same thing via a different route:

1. Place the xess.lib library into the tests directory.
1. Added "changedir=tests" to the tox.ini file so the tests are run in that directory.
1. Replaced the absolute paths in the test files with "xess.lib".

SKiDL looks in the current directory for libraries by default, so these changes make sure it will find the xess.lib file in the local directory.

**Comment by chenz** [comment]
I don't think that is as good a solution

- one might want to run tests without tox
- one might want to run tests outside of the tests directory (ie use the pytest tmpdir fixture)

**Comment by xesscorp** [comment]
I see. How about adding the working directory to the library search path inside `setup_function()`? 

`lib_search_paths[KICAD].append(os.path.dirname(os.path.abspath(__file__)))`

**Comment by chenz** [comment]
Modifying the library path is a specific solution, I still think it is better to have a general solution for the "load a file (not necessarily a library) from the test suite" use case. That is why I implemented it that way. The naming (get_filename) could be better, but hey, that is always the hard part ;-)

Having dedicated test library paths (for example "tests/libs") might still be a good idea. In fact, the tests should really *only* ever use a defined set of libraries, and not whatever happens to be in the user's "KISYSMOD"...

**Comment by xesscorp** [comment]
OK, so:

1. Use `get_filename()` for general-purpose stuff.
1. Use `library_search_paths` for libraries.
1. Clear `library_search_paths` at the beginning to prevent accessing KISYSMOD libraries and then load the current working directory into it.

**Comment by chenz** [comment]
I'm experimenting with this, but the whole library system breaks when you remove the KICAD library from the path. Consider this test:

    def test_backup_1():
        a = Part('device','R',footprint='null')
        b = Part('device','C',footprint='null')
        ....

DEFAULT_TOOL is still KICAD, but of course "device.lib" is no longer on the search path! Funnily enough though, the first line "works". That is because SchLib does not actually check the result of it's loading function. It then also adds it's empty self to the cache.

The second line then crashes, because the Part tries to load itself form the empty "device" lib in cache,  which raises in get_part_by_name.

**Comment by xesscorp** [comment]
I see. How about adding the working directory to the library search path? 

`lib_search_paths[KICAD].append(os.path.dirname(os.path.abspath(__file__)))`

**Comment by xesscorp** [comment]
I'll check the behavior of Part to see why it doesn't report an error on the first invocation.

So should we allow KISYSMOD in the library path during testing, or place a copy of device.lib in the testing directory (similar to what I did with xess.lib)?

**Comment by chenz** [comment]
Yes, providing all required libraries and setting up the search path to use them exclusively is the correct thing to do. Copying device.lib would be the easiest thing. Alternatively, one could change the tests to use SKIDL's device lib, but that would be more work of course, and also not exercise the KICAD loading code in the process.

I see you already made a commit for this, but I don't think that it works. The assignment `tool_lib_path = [os.path.dirname(os.path.abspath(__file__))]` should have no effect at all. 

`tool_lib_path[:] = [os.path.dirname(os.path.abspath(__file__))]` might work.

BTW my version is here: https://github.com/chenz/skidl/tree/tests-lib-search-paths

**Pull request closed without merging**
